### ISSUE TITLE
nusmv variable undefined

### ISSUE THREAD

**Issue by ftc** [cuplv/verivita#214]
Error (python):
```
...
encoding - User time: 5.100000
encoding - System time: 0.220000
INFO:root:Executing /Users/s/software/nuXmv-1.1.1-Darwin/bin/nuXmv -source /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpmweWLkcmd /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpkUlGEFsmv
ERROR:root:Error executing /Users/s/software/nuXmv-1.1.1-Darwin/bin/nuXmv -source /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpmweWLkcmd /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpkUlGEFsmv
Error code is 255
Command line is: /Users/s/software/nuXmv-1.1.1-Darwin/bin/nuXmv -source /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpmweWLkcmd /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpkUlGEFsmv


Traceback (most recent call last):
  File "/Users/s/Documents/source/callback-verification/cbverifier/driver.py", line 466, in <module>
    main()
  File "/Users/s/Documents/source/callback-verification/cbverifier/driver.py", line 442, in main
    (res, cex, mapback) = driver.run_ic3(opts.nuxmv_path, opts.ic3_frames)
  File "/Users/s/Documents/source/callback-verification/cbverifier/driver.py", line 141, in run_ic3
    ic3_frames)
TypeError: 'NoneType' object is not iterable
```

error from nusmv:
```

file /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpkUlGEFsmv: line 605: "var_196" undefined
in definition of define_615 at line 604
in definition of define_2421 at line 1159
in definition of define_2443 at line 2103

aborting 'source /var/folders/53/6550fsxs73g1fpb6_dx9tbpm0000gn/T/tmpmweWLkcmd'
```

command:
```
python driver.py -m ic3 -t manual25.trace.repaired -s execute.spec:activity_callbacks.spec:fragment_callbacks.spec:activity_aux.spec --ic3_frames 40 -n /Users/s/software/nuXmv-1.1.1-Darwin/bin/nuXmv -z
```

files:
[nuxmv_nosuchvar.tar.gz](https://github.com/cuplv/verivita/files/2152246/nuxmv_nosuchvar.tar.gz)

**Comment by ftc** [comment]
Workaround: install smtlib v0.6.1

* pip uninstall pysmt
* git clone https://github.com/pysmt/pysmt/
* cd pysmt; git checkout v0.6.1
* add pysmt directory to PYTHONPATH
* remove ~/.smt_solvers
* python install.py --z3
* python install.py --env
* add env to path
